package com.github.jasonkung.github.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/// Generated by http://www.jsonschema2pojo.org/
@JsonClass(generateAdapter = true)
data class User(
        @field:Json(name = "login")
        var login: String? = null,
        @field:Json(name = "id")
        var id: Int? = null,
        @field:Json(name = "node_id")
        var nodeId: String? = null,
        @field:Json(name = "avatar_url")
        var avatarUrl: String? = null,
        @field:Json(name = "gravatar_id")
        var gravatarId: String? = null,
        @field:Json(name = "url")
        var url: String? = null,
        @field:Json(name = "html_url")
        var htmlUrl: String? = null,
        @field:Json(name = "followers_url")
        var followersUrl: String? = null,
        @field:Json(name = "following_url")
        var followingUrl: String? = null,
        @field:Json(name = "gists_url")
        var gistsUrl: String? = null,
        @field:Json(name = "starred_url")
        var starredUrl: String? = null,
        @field:Json(name = "subscriptions_url")
        var subscriptionsUrl: String? = null,
        @field:Json(name = "organizations_url")
        var organizationsUrl: String? = null,
        @field:Json(name = "repos_url")
        var reposUrl: String? = null,
        @field:Json(name = "events_url")
        var eventsUrl: String? = null,
        @field:Json(name = "received_events_url")
        var receivedEventsUrl: String? = null,
        @field:Json(name = "type")
        var type: String? = null,
        @field:Json(name = "site_admin")
        var siteAdmin: Boolean? = null,
        @field:Json(name = "name")
        var name: String? = null,
        @field:Json(name = "company")
        var company: String? = null,
        @field:Json(name = "blog")
        var blog: String? = null,
        @field:Json(name = "location")
        var location: String? = null,
        @field:Json(name = "email")
        var email: Any? = null,
        @field:Json(name = "hireable")
        var hireable: Boolean? = null,
        @field:Json(name = "bio")
        var bio: String? = null,
        @field:Json(name = "public_repos")
        var publicRepos: Int? = null,
        @field:Json(name = "public_gists")
        var publicGists: Int? = null,
        @field:Json(name = "followers")
        var followers: Int? = null,
        @field:Json(name = "following")
        var following: Int? = null,
        @field:Json(name = "created_at")
        var createdAt: String? = null,
        @field:Json(name = "updated_at")
        var updatedAt: String? = null
)
