package com.github.jasonkung.github.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/// Generated by http://www.jsonschema2pojo.org/
@JsonClass(generateAdapter = true)
data class Users (
        @field:Json(name = "total_count")
        var totalCount: Int? = null,
        @field:Json(name = "incomplete_results")
        var incompleteResults: Boolean? = null,
        @field:Json(name = "items")
        var items: List<User>? = null
)
